#!/usr/bin/env Rscript

args = commandArgs(trailingOnly = TRUE)

if (length(args) == 0L) {
    stop(sprintf('Error: missing argument %s', dQuote('pkg')))
}

verify_is_not_internal = function (file) {
    rd = tools::parse_Rd(file)
    keywords = find_tag(rd, 'keyword')
    is_internal = ! all(vapply(keywords, `!=`, logical(1L), 'internal'))
    ! is_internal || length(find_tag(rd, 'examples')) == 0L
}

find_tag = function (rd, tag) {
    Filter(function (x) attr(x, 'Rd_tag') == paste0('\\', tag), rd)
}

pkg = args[[1L]]

rd_files = dir(file.path(pkg, 'man'), pattern = '\\.[Rr]d$', full.names = TRUE)

ok = vapply(rd_files, verify_is_not_internal, logical(1L))
if (! all(ok)) {
    msg = 'The following internal documentation files have examples:\n  %s'
    failed = basename(rd_files[! ok])
    stop(sprintf(msg, paste(failed, collapse = ',\n  ')))
}
invisible()

# vim: ft=r
